package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"

	"github.com/invopop/jsonschema"
	"github.com/mooneeb/amgi/internal/config"
)

func main() {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		log.Fatal("runtime.Caller failed")
	}

	dir := filepath.Dir(file)
	parent := filepath.Dir(dir)

	r := jsonschema.Reflector{}
	c := r.Reflect(config.Config{})
	c.Comments = "DO NOT MODIFY THIS FILE DIRECTLY. IT IS AUTO-GENERATED BY THE amgi/internal/schema/generate_schema.go."
	data, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		panic(err.Error())
	}
	err = os.WriteFile(fmt.Sprintf("%s/schema.json", parent), data, 0644)
	if err != nil {
		panic(err.Error())
	}
	fmt.Println("Schema generated successfully")
}
