apiVersion: v1
kind: ConfigMap
metadata:
  name: amgi-config
  labels:
    app: amgi
data:
  config.yaml: |
    version: "1"
    github:
      owners:
        - name: your-github-username
          mode: polling
          marvin_config_id: default
          polling_interval_seconds: 300
          repositories:
            - name: your-repo
    marvin:
      configs:
        - id: default
          list_name: "Inbox"
          task:
            title_template: "{{.Type}} #{{.Number}}: {{.Title}}"
            note_template: "{{.URL}}"
