apiVersion: v1
kind: Secret
metadata:
  name: amgi-secrets
  labels:
    app: amgi
type: Opaque
stringData:
  MARVIN_API_TOKEN: "REPLACE_ME"
  GITHUB_WEBHOOK_SECRET: "REPLACE_ME"
  GITHUB_TOKEN: "REPLACE_ME"
